/*
Envprof is a profile-based environment variable manager.

It manages named environment profiles defined in YAML or TOML files,
with support for inheritance, dotenv files, and templating.

Usage:

	envprof [command] [flags]

Use "envprof --help" for more information.
*/
package main

import (
	"fmt"
	"os"

	"github.com/idelchi/envprof/internal/cli"
)

// version is the application version injected at build time.
var version = "unknown - unofficial & generated by unknown"

// main is the entry point of the application.
func main() {
	if err := cli.Execute(version); err != nil {
		fmt.Fprintln(os.Stderr, err)

		os.Exit(1)
	}

	os.Exit(0)
}
