/*
Envprof manages environment variables in profiles.

It provides commands for creating, switching between, and managing different environment configurations.

Usage:

	envprof [command] [flags]

Use "envprof --help" for more information.
*/
package main

import (
	"fmt"
	"os"

	"github.com/idelchi/envprof/internal/cli"
)

// Global variable for CI stamping.
var version = "unknown - unofficial & generated by unknown"

// main is the entry point for the CLI application.
func main() {
	if err := cli.Execute(version); err != nil {
		fmt.Println(err)

		os.Exit(1)
	}

	os.Exit(0)
}
