name: release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"
    paths:
      - "**/*.go"
      - .dockerignore
      - Dockerfile
      - go.mod
      - go.sum
      - .devenv/settings/.goreleaser.yaml

jobs:
  release:
    uses: idelchi/devenv/.github/workflows/gorelease.yml@dev
    permissions:
      contents: write
    with:
      config: .devenv/settings/.goreleaser.yaml
