name: release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  release:
    uses: idelchi/devenv/.github/workflows/gorelease.yml@main
    if: startsWith(github.ref, 'refs/tags/') && !endsWith(github.ref, '-beta')
    permissions:
      contents: write
    with:
      config: .devenv/settings/.goreleaser.yaml
